test:
  key: 123456

redis:
  addr: "43.154.97.245:6379"

db:
  src:
    dsn: "root:root@tcp(43.154.97.245:13316)/webook"
  dst:
    dsn: "root:root@tcp(43.154.97.245:13316)/webook_intr"

kafka:
  addr:
    - "43.154.97.245:9094"

grpc:
  server:
    etcdAddr: "43.154.97.245:12379"
    port: 8090
    name: "interactive"


migrator:
  http:
    addr: ":8082"